### ISSUE TITLE
Error on running d31_scatter_correction.py

### ISSUE THREAD

**Issue by gdidomenico** [LLNL/LEAP#139]
I tried running d31_scatter_correction.py but I always get the following error:

Traceback (most recent call last):
  File "/home/giovanni/software/LEAP/demo_leapctype/d31_scatter_correction.py", line 178, in <module>
    g_dn = leapct_LR.down_sample_projections([1,downSampleFactor,downSampleFactor],g)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/pytorch/lib/python3.11/site-packages/leapctype.py", line 3223, in down_sample_projections
    g_dn = self.down_sample(factors, g)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/pytorch/lib/python3.11/site-packages/leapctype.py", line 1422, in down_sample
    self.libprojectors.down_sample(I, np.array(I.shape), I_dn, np.array(I_dn.shape), factors, True)
ctypes.ArgumentError: argument 2: TypeError: array must have data type int32

Additional info:
- LEAP version 1.25
- conda enviroment with pytorch installed.

**Comment by kylechampley** [comment]
@oooo114 also reported a similar problem in issue #94.  I made some changes and I believe this is fixed now.  Please pull from the [champley_dev](https://github.com/LLNL/LEAP/tree/champley_dev) branch to get the changes.

**Comment by kylechampley** [comment]
Yep, you're correct; I forgot about those other instances.  I just push these changes to the champley_dev branch.
